# Site settings
title: Nura Kawa
email: 
description: > # this means to ignore newlines until "baseurl:"
  Personal Website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nurakawa.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: nurakawa


# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
