title: Nura Kawa
author: Nura Kawa (content), theme by Aigars Dzerviniks
description: personal website

highlighter: null
permalink: /:title

url:
baseurl:
color_scheme: ruby

# Custom options:
# color_scheme: azul|ruby|amber|avocado|black|nura|kawa
# color_scheme: avocado
